name: "Maven release action"
description: "Release a Java project with a maven-release-plugin"
inputs:
  email:
    description: "Email of the initiating user"
    required: true
  profiles:
    description: "Maven profiles that should be activated"
    required: false
  releaseVersion:
    description: "Version to be released"
    required: false
  developmentVersion:
    description: "New development version"
    required: false
  tag:
    description: "Tag name to be used"
    required: false
  prepareArguments:
    description: "-Darguments value that should be passed to a prepare command"
    required: false
  performArguments:
    description: "-Darguments value that should be passed to a perform command"
    required: false
  doNotDeploy:
    description: "Skip deploy step"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
