name: "Maven release action"
description: "Release a Java project with a maven-release-plugin"
inputs:
  token:
    description: "GitHub token"
    required: true
  profiles:
    description: "Maven profiles that should be activated e.g. release"
    required: false
  releaseVersion:
    description: "Version to be released"
    required: false
  # TODO remove
  developmentVersion:
    description: "New development version"
    required: false
   # TODO remove
  tag:
    description: "Tag to be used"
    required: false
  branch:
    description: "Branch which should be released"
    default: "master"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
